#ifndef _DISC_DRIVER_H_
#define _DISC_DRIVER_H_

typedef enum HW_DKC_FUNC{
	HW_DKC_FUNC_SETIRQMODE = 0,
	HW_DKC_FUNC_QUERY = 1,
	HW_DKC_FUNC_READSECTOR = 2, 
	HW_DKC_FUNC_WRITESECTOR = 3
}HW_DKC_FUNC;

typedef enum HW_DKC_INTS{
	HW_DKC_INTS_FINISHED = 0,
	HW_DKC_INTS_MOUNT = 1,
	HW_DKC_INTS_UNMOUNT = 2
}HW_DKC_INTS;


/*#define HW_DKC_ERROR_NOMEDIA 1
#define HW_DKC_ERROR_BUSY 2
#define HW_DKC_ERROR_WRITEPROTECTED 3
#define HW_DKC_ERROR_INVALIDSECTOR 4
#define HW_DKC_ERROR_UNKNOWN 5*/


#endif 