#ifndef _HARDWARE_H_
#define _HARDWARE_H_

#define HWBUS_CPU 0
#define HWBUS_CLK 1
#define HWBUS_SCR 2
#define HWBUS_KYB 3
#define HWBUS_NIC 4
#define HWBUS_DKC 5
#define HWBUS_DEFAULTDEVICES_MAX 6

#define HW_CPU_FUNC_RETRAMAMOUNT 0

#define HW_SCR_FUNC_SCREENINFO 0
#define HW_SCR_FUNC_MAPSCREENBUFFER 1

#define HW_NIC_FUNC_SEND 0 // TODO: it changes to 1, after next release of DevKit

#define HWERR_SUCCESS 0x0
#define HWERR_DEFAULT_DEVICENOTFOUND 0x80000001
#define HWERR_DEFAULT_INVALIDFUNCTION 0x80000002
#define HWERR_DEFAULT_INVALIDMEMORYADDRESS 0x80000003

#define HWDEFAULT_FUNC_QUERYINFO 0x80000000
#define HWDEFAULT_FUNC_QUERYDESC 0x80000001

void hw_initAll(void);



#endif