#ifndef _SDK_KEYBOARD_H_
#define _SDK_KEYBOARD_H_

typedef enum KEY_STATE{
	KEY_STATE_EMPTYBUFFER 	= 0,
	KEY_STATE_KEYPRESSED 	= 1,
	KEY_STATE_KEYRELEASED 	= 2,
	KEY_STATE_KEYTYPED 		= 3
}KEY_STATE;
	
typedef enum KEY_MAP{
	KEY_BACKSPACE 	= 0x01,
	KEY_RETURN 		= 0x02,
	KEY_INSERT 		= 0x03,	
	KEY_DELETE 		= 0x04,	
	KEY_UP 			= 0x05,
	KEY_DOWN 		= 0x06,
	KEY_LEFT 		= 0x07,
	KEY_RIGHT 		= 0x08,	
	KEY_SHIFT 		= 0x09,	
	KEY_CONTROL 	= 0x0A,
	KEY_TAB			= 0x0B
}KEY_MAP;

#endif