#ifndef _SDK_KEYBOARD_H_
#define _SDK_KEYBOARD_H_

typedef enum KEY_STATE{
	KEY_STATE_EMPTYBUFFER = 0,
	KEY_STATE_KEYPRESSED = 1,
	KEY_STATE_KEYRELEASED = 2,
	KEY_STATE_KEYTYPED = 3
}KEY_STATE;
	
#endif